### ISSUE TITLE
Boto3 package integration

### ISSUE THREAD

**Issue by cnouguier** [yagajs/docker-mapproxy#6]
Hi, 
Since version 1.10.0, MapProxy supports S3 backend. However, it requires the boto3 package to be installed (https://mapproxy.org/docs/nightly/caches.html#cache-s3). 
It could be worth to intergrate it. What are your thoughts on this subject?  
Thanks.

**Comment by atd-schubert** [comment]
A good match for micro-services...

**Comment by atd-schubert** [comment]
Added to the version >1.10.0! @cnouguier are you able to test it for us?

**Comment by cnouguier** [comment]
That's really great ! Yes I'll test it and let you know.

**Comment by cnouguier** [comment]
Arne, I have tested  the 1.10.4 and 1.10.4-alpine versions and it works fine (at least the support to the S3 backend). Nervertheless, the MAPPROXY_VERSION environment variable is set to 1.10.1 in the 1.10.4 branch (https://github.com/yagajs/docker-mapproxy/blob/version/1.10.4/Dockerfile#L4). The 1.10.4-alpine branch is ok. I'll open an issue. I'll open an issue
And thank you the work done 👍
